version: '3'

services:
  mysql:
    image: 'mysql:8.1.0'
    platform: linux/x86_64
    restart: always
    volumes:
      - mydata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'hello'
    command: mysqld --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
volumes:
  mydata: